export const data = [{
    name: "Sunny",
    lastName: "Hawken",
    email: "shawken0@nba.com",
    gender: "Female",
    city: "Semboropasar",      
},
{
    name: "Delainey",
    lastName: "Codeman",
    email: "dcodeman1@buzzfeed.com",
    gender: "Male",
    city: "Karagach",      
},
{
    name: "Annnora",
    lastName: "Dunstone",
    email: "adunstone2@dmoz.org	",
    gender: "Female",
    city: "Vilque",      
},
{
    name: "Philippine",
    lastName: "Zelley",
    email: "pzelley3@sohu.com",
    gender: "Female",
    city: "Kallar",      
},
{
    name: "Cobbie",
    lastName: "Smidmoor",
    email: "csmidmoor4@dot.gov",
    gender: "Male",
    city: "Sarrazola",      
},
{
    name: "Shannen",
    lastName: "Fawdrie",
    email: "sfawdrie5@pbs.org",
    gender: "Female",
    city: "Maguling",      
},
{
    name: "Margret",
    lastName: "Livesey",
    email: "mlivesey6@salon.com",
    gender: "Female",
    city: "Chechenglu",      
},
{
    name: "Maynord",
    lastName: "Baines",
    email: "mbaines7@friendfeed.com",
    gender: "Male",
    city: "New Panamao",      
},
{
    name: "Lief",
    lastName: "Ottley",
    email: "lottley8@shutterfly.com",
    gender: "Male",
    city: "Batanamang",      
}]

